language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t islandboy83/docker-book2 -f Dockerfile.dev .

script:
  - docker run -e CI=true islandboy83/docker-book2 npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "docker-book2"
  env: "Dockerbook2-env"
  bucket_name: "elasticbeanstalk-us-west-1-803156002903"
  bucket_path: "docker-book2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_ACCESS_SECRET"
