language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t islandboy83/docker-book2 -f Dockerfile.dev .

script:
  - docker run -e CI=true islandboy83/docker-book2 npm run test
